# Generated by Django 5.2.8 on 2025-11-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseId', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('targetMuscles', models.CharField(max_length=200)),
                ('bodyParts', models.CharField(max_length=200)),
                ('equipments', models.CharField(max_length=100)),
                ('secondaryMuscles', models.CharField(max_length=200)),
                ('gifUrl', models.URLField()),
                ('isTodaysExercise', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercises')),
            ],
            options={
                'verbose_name': 'Exercise History',
                'verbose_name_plural': 'Exercise Histories',
            },
        ),
    ]
