# Generated by Django 5.2.8 on 2025-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercises_secondarymuscles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='grip',
            field=models.CharField(choices=[('pronada', 'Pronada'), ('supinada', 'Supinada'), ('neutra', 'Neutra'), ('mista', 'Mista'), ('nenhuma', 'Nenhuma')], default='nenhuma', max_length=100),
        ),
        migrations.AddField(
            model_name='exercises',
            name='popularity',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=100),
        ),
        migrations.AddField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('empurrar', 'Empurrar'), ('puxar', 'Puxar'), ('core', 'Core'), ('outro', 'Outro')], default='outro', max_length=100),
        ),
    ]
