# Generated by Django 5.2.8 on 2025-11-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercises_grip_exercises_popularity_exercises_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='todayGameDificulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], null=True),
        ),
    ]
