# Generated by Django 5.2.8 on 2025-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercises_todaygamedificulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisehistory',
            old_name='performed_at',
            new_name='performedAt',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='todayGameDificulty',
        ),
        migrations.AddField(
            model_name='exercisehistory',
            name='isNormalMode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='isNormalMode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
