# Generated by Django 5.2.8 on 2025-11-19 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_rename_performed_at_exercisehistory_performedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
